name: CI - BichoFull

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check backend folder
        run: |
          cd backend
          ls
          echo "Backend OK"

      - name: Check frontend folder
        run: |
          cd frontend
          ls
          echo "Frontend OK"